name: benchmark
run-name: ${{ github.actor }} is running a benchmark
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Download clang++
      run: |
            sudo apt-get update && sudo apt-get -y upgrade
            sudo apt-get install clang clang++
    - name: Checkout
      uses: actions/checkout@v2
    - name: Make
      run: make
    - name: Run benchmark
      run: ./bench