name: benchmark
run-name: ${{ github.actor }} is running a benchmark
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Clang
      uses: egor-tensin/setup-clang@v1
      with:
       version: latest
       platform: x64
    - name: Checkout
      uses: actions/checkout@v2
    - name: Make
      run: make
    - name: Run benchmark
      run: ./bench