name: benchmark
run-name: ${{ github.actor }} is running a benchmark
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Make
      run: make
    - name: Run benchmark
      run: ./bench